<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQMCO1OL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQMCO1OL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQMCO1OL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQMCO1OL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQMCO1OL\App_KernelDevDebugContainer([
    'container.build_hash' => 'QMCO1OL',
    'container.build_id' => 'f5ceb84c',
    'container.build_time' => 1599206540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQMCO1OL');
